name: "instruqt"
description: "Publish new instruqt tracks"
inputs:
  trackId: # id of input
    description: "Which track to publish"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.trackId }}
